### ISSUE TITLE
Why it has dependency on SDL?

### ISSUE THREAD

**Issue by MrcSnm** [sezero/SDL_sound#3]
Should not it being able to be used without SDL? As it is only about the decoding things, it does only use the "fopen" and "fread" functions to do it?

**Comment by sezero** [comment]
It uses SDL_RWops and several other SDL_stdinc functionality.
I believe it is intended to have a familiar SDL-like api. Otherwise,
everyone can use the dependent codec libraries themselves,
already.

These questions are best asked at https://discourse.libsdl.org/
forum, and issues patches reported at https://bugzilla.libsdl.org/
Because this is _only a mirror_.
